STATUS = {
  'SUCCESS': 'success',
  'ERROR': 'error',
}
CODE = {
  'DATA_SAVED': 'DATA_SAVED',
  'DATA_LOADED': 'DATA_LOADED',
  'DATA_FETCHED': 'DATA_FETCHED',
  'DATA_NOT_FOUND': 'DATA_NOT_FOUND',
  'FILE_NOT_FOUND': 'FILE_NOT_FOUND',
  'INVALID_JSON': 'INVALID_JSON',
  'UNKNOWN_KEY': 'UNKNOWN_KEY',

  'MISSING_REQUIRED_DATA': 'MISSING_REQUIRED_DATA',
  'DUPLICATE_DATA': 'DUPLICATE_DATA',
  'INVALID_UID': 'INVALID_UID',
  'INVALID_USERNAME': 'INVALID_USERNAME',
  'INVALID_PASSWORD': 'INVALID_PASSWORD',
  'INVALID_EMAIL': 'INVALID_EMAIL',
  'DATA_VALID': 'DATA_VALID',
  
  'FAILED_LOGIN': 'FAILED_LOGIN',
}